[package]
name = "concrete_jungle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete = { version = "0.2.0", features = [ "booleans", "shortints", "integers", "serde"] }
rand = "0.8.5"